### ISSUE TITLE
Where can I find your dataset?

### ISSUE THREAD

**Issue by jinningli** [elaaf/stance-detect#1]
I am trying to run your code, is it possible for me to download your dataset whose path is `stance_detect/datasets/twitter_covid.csv` in your code? Thank you!

**Comment by elaaf** [comment]
Hi there, unfortunately I can not provide the full dataset. I have added a small sample dataset for ease of running the code. You can modify your dataset OR simply use the load_dataset function to adjust the code to your dataset.
